CREATE SCHEMA IF NOT EXISTS transportation_expense_bot;					-- スキーマ存在確認
DROP TABLE IF EXISTS transportation_expense_bot."SERVER_TOKEN_INFO";	-- DB存在確認
CREATE TABLE transportation_expense_bot."SERVER_TOKEN_INFO" (
	"ID" INT DEFAULT 1 NOT NULL
	,"TOKEN" VARCHAR(1000) NOT NULL
	,"START_FROM" TIMESTAMP(6) WITH TIME ZONE
	,"END_AT" TIMESTAMP(6) WITH TIME ZONE NOT NULL
	,PRIMARY KEY ("ID")
);
